### ISSUE TITLE
netvsc_start_xmit error in netvsc_drv.c

### ISSUE THREAD

**Issue by chvalean** [LIS/lis-next#116]
Compiling lis-next on centos 6.0 64bit (kernel 2.6.32-71.el6.x86_64) fails with the below:

/root/lis-next/hv-rhel6.x/hv/netvsc_drv.c: In function ‘netvsc_start_xmit’:
/root/lis-next/hv-rhel6.x/hv/netvsc_drv.c:656: error: implicit declaration of function ‘skb_tx_timestamp’
make[1]: *** [/root/lis-next/hv-rhel6.x/hv/netvsc_drv.o] Error 1

**Comment by nickme** [comment]
Resolved in commit:  a4f19b119508f38a9dc8eb618761600c24f80829
