### ISSUE TITLE
netvsc crash due to commit "hv_netvsc: Add UDP RSS support for rhel 6.x"

### ISSUE THREAD

**Issue by chvalean** [LIS/lis-next#129]
centos 6.7 32bit does not boot after lis-next installation.
Guest is crashing with a kernel panic later in the boot process, with a pointer to netvsc_set_hash.
this is repro only on 32bit, patch is working fine on 7.x and 6.x 64bit.

**Comment by simonxiaoss** [comment]
Fixed by patch d0759d3
