### ISSUE TITLE
Cannot build lis-next on RHEL 6.4 x64

### ISSUE THREAD

**Issue by zsoltdudas** [LIS/lis-next#157]
Trying to build lis-next on RHEL 6.4 x64 with kernel 2.6.32-358.56.1.el6.x86_64 I get the following error:

`[root@localhost hv]# ./rhel${rhel_version}-hv-driver-install
Building Modules
make: Entering directory `/usr/src/kernels/2.6.32-358.56.1.el6.x86_64'
make: Leaving directory `/usr/src/kernels/2.6.32-358.56.1.el6.x86_64'
make: Entering directory `/usr/src/kernels/2.6.32-358.56.1.el6.x86_64'
  CC [M]  /root/lis-next/hv-rhel6.x/hv/netvsc_drv.o
  CC [M]  /root/lis-next/hv-rhel6.x/hv/netvsc.o
  CC [M]  /root/lis-next/hv-rhel6.x/hv/rndis_filter.o
  CC [M]  /root/lis-next/hv-rhel6.x/hv/af_hvsock.o
/root/lis-next/hv-rhel6.x/hv/af_hvsock.c: In function ‘hvsock_getname’:
/root/lis-next/hv-rhel6.x/hv/af_hvsock.c:424: error: implicit declaration of function ‘__sockaddr_check_size’
make[1]: *** [/root/lis-next/hv-rhel6.x/hv/af_hvsock.o] Error 1
make: *** [_module_/root/lis-next/hv-rhel6.x/hv] Error 2
make: Leaving directory `/usr/src/kernels/2.6.32-358.56.1.el6.x86_64'
Wed Sep 07 11:39:10 2016 : Error: Unable to build the lis-next RHEL 6 code`

**Comment by v-vyadav** [comment]
Fixed in lis-next.
