### ISSUE TITLE
KVP OS distro version detection improvement

### ISSUE THREAD

**Issue by chvalean** [LIS/lis-next#169]
The KVP daemon is using /etc/os-release to report the OSMajorVersion key.

If the file does not exist, it falls back to /etc/redhat-release.  The fallback code assumes the file has multiple lines of content, which is incorrect.  Temporary workaround is to install the RPM that provides the /etc/os-release file.

The code will be updated for the fallback parsing code to handle the contents of /etc/redhat-release for both RedHat and CentOS.

**Comment by nickme** [comment]
Resolved.  The daemon now processes the *-release files correctly.
