### ISSUE TITLE
RHEL 6.x 32 bit not booting

### ISSUE THREAD

**Issue by paulaCrismaru** [LIS/lis-next#181]
On RHEL 6.2, 6.6 and 6.8, all 32 bit with LIS-next, the VMs are not booting when multiple External NICs are attached. On 6.4 and 7.0  64 bit it works as expected.

**Comment by nickme** [comment]
With the changes to make the ring buffer wrap, the amount of virtual memory required has increased.  If the 32 bit VMs have more than 2 syntheitic NICs, you will need to us the boot option vmalloc=<size> to increase the size of the malloc area.  Default is 128MB.  For each additional NIC, increase vmalloc by about 80MB.  For example a 32 bit VM with 3 synthetic NICs use vmalloc=208.
Note: 64 bit systems have a default vmalloc size of 1024MB.
