### ISSUE TITLE
Check if daemon guest service is enabled, gracefully exit if not.

### ISSUE THREAD

**Issue by nickme** [LIS/lis-next#214]
If the guest service for each daemon is enabled, you can find the guest service GUID under:
    /sys/bus/vmbus/drivers/hv_util/vmbus_*/class_id
Add a check to the daemons to verify their guest service is enabled.  If not, log an informational message and exit gracefully.

Following is prototype code:

char HV_UTIL_ROOT_DIR[] = "/sys/bus/vmbus/drivers/hv_util";

char KVP_GUID[]   = "{a9a0f4e7-5a45-4d96-b827-8a841e8c03e6}";
char VSS_GUID[]   = "{35fa2e29-ea23-4236-96ae-3a6ebacba440}";
char FCOPY_GUID[] = "{34d14be3-dee4-41c8-9ae7-6b174977c192}";

/*
 * check_class_id()
 *
 * Try to open the class_id entry under the directory.
 * If successful, read the class_id string and see if
 * it matches our GUID.
 */
int check_class_id(char *dirname, char *classid)
{
        int  f;
        int  isEnabled = 0;
        char filename[256];
        char buf[256];

        sprintf(filename, "%s/%s/class_id", HV_UTIL_ROOT_DIR, dirname);

        f = open(filename, O_RDONLY);
        if (f > 0)
        {
                memset(buf, 0, 256);
                read(f, buf, 255);
                if (! (strncmp(classid, buf, 38)))
                        isEnabled = 1;
                close(f);
        }

        return isEnabled;
}

/*
 * is_service_enabled()
 *
 * Open the hv_util directory in the sysfs directory.
 * Then check all subdirectories for a class_id that
 * matches our GUID.
 */
int is_service_enabled(char *serviceGUID)
{
        int    isEnabled = 0;
        DIR    *dir;
        struct dirent *ent;

        if (! (dir = opendir(HV_UTIL_ROOT_DIR)))
                return 0;

        /* Note: The vmbus_nn entries are links, not DT_DIR entries */
        while ((ent = readdir(dir)))
                if (ent->d_type == DT_LNK)
                        if (check_class_id(ent->d_name, serviceGUID))
                        {
                                isEnabled = 1;
                                break;
                        }
        closedir(dir);
        return isEnabled;
}

**Comment by vyadavmsft** [comment]
Already fix.
