### ISSUE TITLE
warning in hv_fcopy_daemon.c file 6.x

### ISSUE THREAD

**Issue by paulaCrismaru** [LIS/lis-next#219]
The bellow warning appears when compiling hv_fcopy_daemon.c for 6.x branch 4.1.3

gcc -Wall -Wextra -g -lpthread -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D__EXPORTED_HEADERS__ -I../include/uapi -I ../include -o hv_fcopy_daemon hv_fcopy_daemon.c
hv_fcopy_daemon.c: In function ‘hv_copy_data’:
hv_fcopy_daemon.c:109: warning: comparison between signed and unsigned integer expressions

**Comment by nickme** [comment]
The HV_DRV_VERSION has been moved out of the kernel only section of hv_compat.h.
