### ISSUE TITLE
error compiling lis-next on rhel/centos 6.0 and 6.2x32

### ISSUE THREAD

**Issue by paulaCrismaru** [LIS/lis-next#224]
The following error appears when compiling LIS-next branch 4.1.3 on 6.0 and 6.2x32.

gcc -Wall -Wextra -g -lpthread  -D__EXPORTED_HEADERS__ -I../include/uapi -I ../include -o hv_kvp_daemon hv_kvp_daemon.c
In file included from ../include/uapi/linux/hyperv.h:33,
                 from hv_kvp_daemon.c:36:
../include/uapi/linux/../../linux/hv_compat.h:639:31: error: linux/etherdevice.h: No such file or directory
In file included from ../include/uapi/linux/hyperv.h:33,
                 from hv_kvp_daemon.c:36:
../include/uapi/linux/../../linux/hv_compat.h:647: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘ether_addr_equal’
make: *** [hv_kvp_daemon] Error 1

**Comment by nickme** [comment]
Resolved.  Fix part of pull request #222.
