### ISSUE TITLE
RHEL 7 latest kernel breaking LIS integration

### ISSUE THREAD

**Issue by chvalean** [LIS/lis-next#296]
RHEL recently published kernel 3.10.0-514.10.2.el7.x86_64.
If we install LIS 4.1.3-1 on top of the new kernel, after reboot the VM will hang and fail to boot.

This has been reported by two users using the v-magine OpenStack deployment [in this thread](https://ask.cloudbase.it/question/2070/v-magine-install-fail-a-start-job-is-running-for-dev-mapp/)

All LIS modules report unknown symbols at boot time, including storvsc, which fails to load. This leads to dracut-initqueue timeout messages.
A few sample boot messages for reference:

> [    1.304404] hv_storvsc: disagrees about version of symbol vmbus_driver_unregister
> [    1.304406] hv_storvsc: Unknown symbol vmbus_driver_unregister (err -22)
> [    1.304731] hv_storvsc: Unknown symbol __vmbus_driver_register (err -22)
> [    1.304737] hv_storvsc: disagrees about version of symbol vmbus_sendpacket_mpb_desc
> [    1.304738] hv_storvsc: Unknown symbol vmbus_sendpacket_mpb_desc (err -22)
> [    1.304740] hv_storvsc: disagrees about version of symbol vmbus_are_subchannels_present
> [    1.304740] hv_storvsc: Unknown symbol vmbus_are_subchannels_present (err -22)

**Comment by vyadavmsft** [comment]
Fixed now.
