### ISSUE TITLE
LIS not compatible with latest kernels 3.10.0-693 or 3.10.0-693.1.1

### ISSUE THREAD

**Issue by jas612** [LIS/lis-next#429]
From install.sh:

regex='3.10.0-514.10+\.[0-9]+'
regex1='3.10.0-514.16.1'
regex2='3.10.0-514.21.1'
regex3='3.10.0-514.21.2'
regex4='3.10.0-514.26.1'
regex5='3.10.0-514.26.2'

I don't see 3.10.0-693 or 3.10.0-693.1.1 in there and it causes the exact same symptoms as https://github.com/LIS/lis-next/issues/343.  Please advise.

**Comment by shirgall** [comment]
The next release, 4.2.3, adds compatibility for the 7.4 kernels.

**Comment by jas612** [comment]
I see.  Okay.  I am using a CentOS derivative in Scientific Linux.  I guess they upgraded kernel before CentOS official did, as all their 7.x versions now have this kernel.  Supported OS wise, this project supports CentOS and RHEL as far as Redhat based distributions go, and nothing else, correct?  Where is most appropriate to submit a request for Scientific Linux support, if so?

**Comment by johanburati** [comment]
When do you plan to release 4.2.3 ? 

Without it, it is not possible to install the NVIDIA driver, the only kernel-devel package available on RHUI is for 3.10.0-693

**Comment by shirgall** [comment]
We plan to release 4.2.3 very soon, as early as this week.

Thanks, --jrp

**Comment by chvalean** [comment]
Hi @jas612!
LIS 4.2.3 has been released, you can find it here: https://github.com/LIS/lis-next/releases/tag/v4.2.3
It has support for all RHEL/CentOS kernels to date.

**Comment by jas612** [comment]
Confirmed working, thank you!
