### ISSUE TITLE
LIS 4.2.4-beta1 - Hot Remove NIC VM failure

### ISSUE THREAD

**Issue by chvalean** [LIS/lis-next#468]
Hot removing the network adapter causes the VM to crash.
Gen2 VM crashes when we try to hot remove a network adapter after installing LIS 4.2.4-beta1.

**Comment by chvalean** [comment]
Seems to be resolved in latest daily lis-next and 4.2.4.

**Comment by dcui** [comment]
It looks there is no code change? I guess it  just became not so easy to repro?

**Comment by chvalean** [comment]
There have been at least 4 netvsc related commits added in 4.2.4 since Beta1, those solved it.

**Comment by dcui** [comment]
I think it's https://github.com/LIS/lis-next/commit/81d32315e94a69595b108b0491dca665cc883f0e that fixed the issue: previously we called unregister_netdevice() twice due to a backport issue. :-)
