### ISSUE TITLE
disable/enable integration services failure in 4.2.4

### ISSUE THREAD

**Issue by chvalean** [LIS/lis-next#478]
Regression from 4.2.3-1.

Tests that disable/enable integration services fail (eg. KVP and FCopy), because the daemon cannot be started after a disable/enable cycle. The daemons enter a failed state and cannot be started.

**Comment by dcui** [comment]
I suppose the the fix https://github.com/LIS/lis-next/commit/f25d370438bed9e5e6d1cfd344355a399054ee20 should fix this bug.
The fix has been merged to 4.2.4.

**Comment by chvalean** [comment]
Confirmed as resolved on both 6.x and 7.x in lis-next post 4.2.4 Beta 1.
