### ISSUE TITLE
Performance issues in 4.2.4 Beta

### ISSUE THREAD

**Issue by chvalean** [LIS/lis-next#483]
1. Very low repro rate on rhel 6.8 for a call trace during network performance run.
2. Low SR-IOV throughput on rhel 7.3.

**Comment by chvalean** [comment]
Update:
1. Very low repro rate on rhel 6.8 for a call trace during network performance run.
    > Found no repro.

2. Low SR-IOV throughput on rhel 7.3.
    > Found bad commit as https://github.com/LIS/lis-next/commit/e6ca712a76b12f09f5f095e5095e23cad9bae28b

**Comment by dcui** [comment]
https://github.com/LIS/lis-next/pull/508 should fix this issue.

**Comment by chvalean** [comment]
Fix validated on Beta7, closing bug.
