### ISSUE TITLE
Not able to install LIS on RHEL 6.X

### ISSUE THREAD

**Issue by vinodkumar88** [LIS/lis-next#51]
Hi,

Please help us we are not able to install this LIS on RHEL6.x x86_64

]# ./rhel6-hv-driver-install
Building Modules
make: *** /lib/modules/2.6.32-504.el6.x86_64/build: No such file or directory.  Stop.
]#
]# make -C /lib/modules/$(uname -r)/build M=`pwd` clean
make: *** /lib/modules/2.6.32-504.el6.x86_64/build: No such file or directory.  Stop.
]#

]# cat /etc/redhat-release
Red Hat Enterprise Linux Server release 6.6 (Santiago)
]#
]# uname -r
2.6.32-504.el6.x86_64
]#

**Comment by nickme** [comment]
Hi there,

Thank you for the report.  The RHEL 6.6 release includes the 2.6.32-504 kernel.  The problem statement in the original email shows the path as:
        /lib/modules/2632-504el6x86_64/build
Also, uname is returning:
        2632-504el6x86_64

The periods are missing.  It should be:
        /lib/modules/2.6.32-504.el6.x86_64
and uname should be returning:
        2.6.32-504.el6.x86_64

As a quick test, I used an existing 6.6 x64 VM I had on a test server.  ‘uname -r’ does return ‘2.6.32-504.el6.x86_64’.  Building LIS was successful.

Questions:
        Did someone rebuild the kernel and modify the kernel version string?

        Look in the /lib/modules/ directory.  Is there a directory named 2.6.32-504.el6.x86_64?
                If yes, you can try renaming it to 2632-504el6x86_64, but I believe you will run into other issues.
                Removing the periods from the version string could break some macros used in building.

Hope this helps,

-Nick Meier
Microsoft Linux Integrated Services team.

**Comment by vinodkumar88** [comment]
Thanks Nick, for the update.


This is My fresh new build OS and there is no any changes with kernel and
OS.

Kernel version is 2.6.32-504.el6.x86_64 (default came with RHEL 6.6  x86_64)

/lib/modules/2.6.32-504.el6.x86_64/build  file is present in the operating
system (OS) and this is pointing to the file
 /usr/src/kernels/2.6.32-504.el6.x86_64 which is not present.

Please check below command for better understanding.

=============================================================================================
[root@indusdracmsdb1 hv]# ./rhel6-hv-driver-install
Building Modules
make: *** /lib/modules/2.6.32-504.el6.x86_64/build: No such file or
directory.  Stop.
[root@indusdracmsdb1 hv]#
[root@indusdracmsdb1 hv]# ls -l /lib/modules/2.6.32-504.el6.x86_64/build
lrwxrwxrwx. 1 root root 46 Mar  5  2015
/lib/modules/2.6.32-504.el6.x86_64/build ->
../../../usr/src/kernels/2.6.32-504.el6.x86_64
[root@indusdracmsdb1 hv]#
[root@indusdracmsdb1 hv]# ls -la /usr/src/kernels/
total 8
drwxr-xr-x. 2 root root 4096 Nov  1  2011 .
drwxr-xr-x. 4 root root 4096 Mar  5  2015 ..
[root@indusdracmsdb1 hv]#

===========================================================================================

I just want to say that /usr/src/kernels does not have any file or
directory with the name of kernel version i.e. 2.6.32-504.el6.x86_64

I am also facing same issue with RHEL 6.4 and 6.7

Thanks
Vinod Kumar

**Comment by nickme** [comment]
Hi Vinod,

Great - that is progress.  I believe the issue you are now running into is due to a package missing.  I believe a group install of the Development Tools will install all the packages required to build kernel components.  Try the following command, then give building LIS another try:

                yum groupinstall “Development Tools”

thanks,

-Nick

**Comment by v-vyadav** [comment]
You need to install kernel-devel package to build LIS from source.  

# yum install kernel-devel Or download it from ISO. 

Thanks
Vivek

**Comment by vinodkumar88** [comment]
Thank you very much NIck,

My issue has been solved and now LUN's are visible on Linux VM.


Thanks
Vinod Kumar
vkrhce12@gmail.com
