### ISSUE TITLE
PowerShell shutdown IC on WS2012 issue

### ISSUE THREAD

**Issue by chvalean** [LIS/lis-next#510]
shtudown IC from PowerShell on WS2012 will report the status as not available.
Power controls do work from the UI.

**Comment by santoshx** [comment]
@chvalean 
Is this an issue even in latest release 4.2.8 ?

**Comment by chvalean** [comment]
Verified this again now with WS2012 and RHEL 7.5 guest VM + LIS 4.3.0.
The problem does no longer reproduce, closing this issue.
