### ISSUE TITLE
RH7.5 kernel update results in symbol version mismatches

### ISSUE THREAD

**Issue by adanielov** [LIS/lis-next#539]
After installing kmod-microsoft-hyper-v-4.2.5-20180524.x86_64 on 3.10.0-862.el7 kernel everything works well and the newly installed modules are loaded. But after updating the kernel to 3.10.0-862.3.2.el7 the installed modules cannot be loaded and the old built-in modules are used again.

I understand that kmod for rpm for 3.10.0-862.3.2.el7 is available under update2 directory. However, my understanding is that the purpose of kmod is to automatically re-use already installed modules after minor kernel updates. Minor kernel updates should not break symbols.

**Comment by chvalean** [comment]
Hi @adanielov,
Latest LIS 4.2.5-2 release has support for the latest RHEL\CentOS 3.10.0-862 series kernel.
These minor releases are due to the kABI changes in the kernel, so you will have to update LIS if the kernel gets updated.

**Comment by chvalean** [comment]
@adanielov closing this issue now if there are no further questions, please re-open if needed.
Thank you!
