### ISSUE TITLE
ndo_get_stats64 pointer type warning

### ISSUE THREAD

**Issue by chvalean** [LIS/lis-next#551]
This appears on all 7.x during compile.

  CC [M]  /lis-next/hv-rhel7.x/hv/netvsc_drv.o
/lis-next/hv-rhel7.x/hv/netvsc_drv.c:1666:2: warning: initialization from incompatible pointer type [enabled by default]
  .ndo_get_stats64 =  netvsc_get_stats64,
  ^
/lis-next/hv-rhel7.x/hv/netvsc_drv.c:1666:2: warning: (near initialization for 'device_ops.ndo_get_stats64') [enabled by default]
  CC [M]  /lis-next/hv-rhel7.x/hv/netvsc.o

**Comment by vyadavmsft** [comment]
This is fixed in master. please check and close.
