### ISSUE TITLE
Any issue applying 4.2.6 to unsupported newer RHEL7.5 kernel?

### ISSUE THREAD

**Issue by oniled** [LIS/lis-next#596]
LISISO/RHEL75/install.sh currently supports up to 3.10.0-862.11.6

Current RHEL7.5 kernel is 3.10.0-862.14.4.el7

I jerry-rigged the install.sh  by editing

regex6='3.10.0-862.11.6'

to 

regex6='3.10.0-862.14.4'

Before doing so I would receive a "Kernel version not supported, exiting."
-----

Are there any issues applying lis-rpms-4.2.6 to this newer kernel?  Here is the output of the modinfo command:

[user@server~]$ /sbin/modinfo hv_vmbus
filename:       /lib/modules/3.10.0-862.14.4.el7.x86_64/weak-updates/microsoft-hyper-v/hv_vmbus.ko
version:        4.2.6
license:        GPL
retpoline:      Y
rhelversion:    7.5
srcversion:     581BFCB32D09E7A1B019591
alias:          acpi*:VMBus:*
alias:          acpi*:VMBUS:*
depends:
vermagic:       3.10.0-862.11.6.el7.x86_64 SMP mod_unload modversions
parm:           affinity_mode:vmbus channel cpu affinity mode: 0, 1 (int)

**Comment by santoshx** [comment]
@oniled 
Please use the latest release 4.8.0 which supports kernel 3.10.0-862.14.4.
You may please close this issue.

**Comment by oniled** [comment]
Thanks, this is resolved by lis-rpms 4.2.8
