### ISSUE TITLE
lis-rpms 4.2.8 shows incorrect version in Failover Cluster Manager

### ISSUE THREAD

**Issue by oniled** [LIS/lis-next#631]
This is a screenshot of a linux VM with lis-rpms-4.2.6 installed.  Centos 3.10.0-862.11.6.el7.x86_64

![image](https://user-images.githubusercontent.com/8421682/51925515-170f5400-23a4-11e9-9b69-d7e527a1897d.png)

This is a screenshot of a linux VM with lis-rpms-4.2.8 installed.  Centos 3.10.0-957.1.3.el7.x86_64

![image](https://user-images.githubusercontent.com/8421682/51925643-5f2e7680-23a4-11e9-9330-8a0767dbf906.png)

**Comment by santoshx** [comment]
@oniled
Can your provide output of "modinfo hv_netvsc"  from both VMs?

**Comment by santoshx** [comment]
You do not have 4.2.8 installed on VM where you don't see 4.2.8.
Was your installation a success?

**Comment by oniled** [comment]
Ah I see the problem now.

I did the following

1. on the old kernel, ran upgrade.sh to upgrade from 4.2.6 to 4.2.8. rebooted.
2. ran yum update and updated the kernel to the latest version. rebooted.
3. ran modinfo hv_netvsc and it showed the missing version.

i should have installed the latest kernel before running the upgrade.sh.  

Thanks for your help again @santoshx

**Comment by santoshx** [comment]
@oniled  You may close the issue.
