### ISSUE TITLE
Loading uio_hv_generic causes crash on CentOS 7.6

### ISSUE THREAD

**Issue by mgsmith1000** [LIS/lis-next#647]
On a CentOS 7.6 VM running in Azure (Standard DS3 v2 with 2 accelerated NICs), after installing the LIS 4.2.8 or LIS 4.2.8-1 RPMs from https://www.microsoft.com/en-us/download/details.aspx?id=55106 and running 'modprobe uio_hv_generic', the VM crashes.

The crash dump dmesg output looks like this:

[  662.414212] hv_vmbus: registering driver uio_hv_generic
[  662.422332] BUG: unable to handle kernel NULL pointer dereference at           (null)
[  662.423305] IP: [<ffffffffb717f609>] memcmp+0x9/0x50
[  662.423305] PGD 800000038e3d5067 PUD 38e366067 PMD 0 
[  662.423305] Oops: 0000 [#1] SMP 
[  662.423305] Modules linked in: uio_hv_generic(OE+) nf_conntrack_ipv4 nf_defrag_ipv4 xt_owner xt_conntrack nf_conntrack iptable_security uio_pci_generic ib_isert iscsi_target_mod ib_srpt target_core_mod ib_srp scsi_transport_srp ib_ucm rpcrdma sunrpc rdma_ucm ib_uverbs ib_iser rdma_cm ib_umad iw_cm libiscsi ib_ipoib scsi_transport_iscsi ib_cm sb_edac iosf_mbi crc32_pclmul joydev ghash_clmulni_intel aesni_intel lrw gf128mul glue_helper ablk_helper cryptd mlx4_ib ib_core sg pcspkr i2c_piix4 igb_uio(OE) uio ip_tables xfs libcrc32c mlx4_en mlx4_core devlink pci_hyperv(OE) sd_mod crc_t10dif crct10dif_generic hv_netvsc(OE) hid_hyperv(OE) hv_storvsc(OE) hv_utils(OE) scsi_transport_fc hv_balloon(OE) ptp scsi_tgt hyperv_keyboard(OE) pps_core hyperv_fb(OE) crct10dif_pclmul crct10dif_common crc32c_intel ata_generic
[  662.423305]  pata_acpi floppy serio_raw ata_piix libata hv_vmbus(OE)
[  662.423305] CPU: 0 PID: 6058 Comm: insmod Kdump: loaded Tainted: G           OE  ------------   3.10.0-957.el7.x86_64 #1
[  662.423305] Hardware name: Microsoft Corporation Virtual Machine/Virtual Machine, BIOS 090007  06/02/2017
[  662.423305] task: ffff8c227a796180 ti: ffff8c248e39c000 task.ti: ffff8c248e39c000
[  662.423305] RIP: 0010:[<ffffffffb717f609>]  [<ffffffffb717f609>] memcmp+0x9/0x50
[  662.423305] RSP: 0018:ffff8c248e39fc00  EFLAGS: 00010202
[  662.423305] RAX: ffff8c2528709000 RBX: 0000000000000000 RCX: ffffffffb72a85f0
[  662.423305] RDX: 0000000000000010 RSI: ffffffffc0403f10 RDI: 0000000000000000
[  662.423305] RBP: ffff8c248e39fc00 R08: ffff8c25290ebcd8 R09: 0000000000000000
[  662.423305] R10: ffff8c252f61f380 R11: ffffed81ce9e8400 R12: ffff8c2528709000
[  662.423305] R13: ffffffffb72a85f0 R14: 0000000000000000 R15: ffffffffc094d0c0
[  662.423305] FS:  00007fe9b1870740(0000) GS:ffff8c252f600000(0000) knlGS:0000000000000000
[  662.423305] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[  662.423305] CR2: 0000000000000000 CR3: 000000038e3ac000 CR4: 00000000001406f0
[  662.423305] Call Trace:
[  662.423305]  [<ffffffffc03f4236>] hv_vmbus_get_id+0x26/0x60 [hv_vmbus]
[  662.423305]  [<ffffffffc03f57a4>] vmbus_match+0x34/0x40 [hv_vmbus]
[  662.423305]  [<ffffffffb72a8616>] __driver_attach+0x26/0xa0
[  662.423305]  [<ffffffffb72a85f0>] ? __device_attach+0x50/0x50
[  662.423305]  [<ffffffffb72a5e25>] bus_for_each_dev+0x75/0xc0
[  662.423305]  [<ffffffffb72a7bfe>] driver_attach+0x1e/0x20
[  662.423305]  [<ffffffffb72a76a0>] bus_add_driver+0x200/0x2d0
[  662.423305]  [<ffffffffb72a8d14>] driver_register+0x64/0xf0
[  662.423305]  [<ffffffffc03f56c7>] __vmbus_driver_register+0x57/0x60 [hv_vmbus]
[  662.423305]  [<ffffffffc06f4000>] ? 0xffffffffc06f3fff
[  662.423305]  [<ffffffffc06f401e>] hyperv_module_init+0x1e/0x1000 [uio_hv_generic]
[  662.423305]  [<ffffffffb6e0210a>] do_one_initcall+0xba/0x240
[  662.423305]  [<ffffffffb6f18f8c>] load_module+0x272c/0x2bc0
[  662.423305]  [<ffffffffb71a3030>] ? ddebug_proc_write+0x100/0x100
[  662.423305]  [<ffffffffb6f14b13>] ? copy_module_from_fd.isra.44+0x53/0x150
[  662.423305]  [<ffffffffb6f19606>] SyS_finit_module+0xa6/0xd0
[  662.423305]  [<ffffffffb7574ddb>] system_call_fastpath+0x22/0x27
[  662.423305] Code: 66 90 55 31 c9 48 85 d2 48 89 f8 48 89 e5 74 0f 66 90 48 89 34 c8 48 83 c1 01 48 39 d1 75 f3 5d c3 90 55 48 85 d2 48 89 e5 74 3c <0f> b6 07 0f b6 0e 29 c8 75 27 48 83 ea 01 31 c9 eb 1a 0f 1f 44 
[  662.423305] RIP  [<ffffffffb717f609>] memcmp+0x9/0x50
[  662.423305]  RSP <ffff8c248e39fc00>
[  662.423305] CR2: 0000000000000000

**Comment by johnsongeorge-w** [comment]
This issue is fixed in master and it will be released with the next LIS release.
PR: https://github.com/LIS/lis-next/pull/584

**Comment by chvalean** [comment]
@mgsmith1000 please update to the latest LIS 4.3.0 to fix this issue.
https://github.com/LIS/lis-next/releases/tag/v4.3.0

Thank you!
