### ISSUE TITLE
Kernel version not supported, Exiting. (3.10.0-957.12.1.el7.x86_64)

### ISSUE THREAD

**Issue by psyapathy** [LIS/lis-next#709]
Hello!

I trying install LIS on my server with Centos 7 (Kernel 3.10.0-957.12.1.el7.x86_64).
But i get error "Kernel version not supported, Exiting."
How i can install LIS on my kernel?

Thank you advance

**Comment by santoshx** [comment]
LIS 4.3.1-1 will have support for kernel 3.10.0-957.12.1.
