### ISSUE TITLE
Kernel version not supported, Exiting. (3.10.0-957.12.2.el7.x86_64)

### ISSUE THREAD

**Issue by Torsin** [LIS/lis-next#714]
4.3.1-1 added support for 3.10.0-957.12.1.el7.x86_64, but now 3.10.0-957.12.2.el7.x86_64 is available and LIS does not support the newest.  Thank you for all you do.

**Comment by johnsongeorge-w** [comment]
Kernel-3.10.0-957.12.2.el7.x86_64 is supported in 4.3.2 release.

**Comment by Torsin** [comment]
Yep, 4.3.2 installed and appears to be working without issue.
