### ISSUE TITLE
Port lsvmbus to 5.x

### ISSUE THREAD

**Issue by alexngmsft** [LIS/lis-next#91]

**Comment by nickme** [comment]
The line of code causing the panic is in channel.c, function vmbus_get_debug_info:
debuginfo->clientmonitor_connectionid = 
        monitorpage->parameter[monitor_group][monitor_offset].connectionid.u.id;

monitor_group and monitor_offset are set as:
    u8 monitor_group = (u8)channel->offermsg.monitorid / 32; 
    u8 monitor_offset = (u8)channel->offermsg.monitorid % 32;

The channel->offermsg.monitorid = 255.  This results in monitor_group and monitor_offset being set to the following:
    monitor_group = 7
    monitor_offset = 31

In hyperv_vmbus.h, the hv_monitor_page structure defines the parameter variable as:
struct hv_monitor_parameter    parameter[4][32];

The computed value for monitor_group is greater than 4.

Using instrumentation and querying device_id for each vmbus id, for most VMBus devices the monitorid is 255.
    VMBUS ID   Monitorid
    ========	=========
    vmbus_1       0
    vmbus_2     255
    vmbus_3     255
    vmbus_4     255
    vmbus_5       2
    vmbus_6     255
    vmbus_7     255
    vmbus_8     255
    vmbus_9     255
    vmbus_10    255
    vmbus_11    255
    vmbus_12    255
    vmbus_13    255
    vmbus_14      1

A monitorid of 255 looks to be a valid value.   On some 5.x version, reading the device_id when the monitorid is 255 results in a panic, but not all 5.x version.  Speculation is that when we reference past the end of the array, on some systems, there is a valid page at the address, and on others, the page is invalid, hence the panic.

Proposed solution:
    change
        u8 monitor_group = (u8)channel->offermsg.monitorid / 32; 
    to
        u8 monitor_group = (u8)channel->offermsg.monitorid / 64; 
The will keep the value of monitor_group within the range of 0-3.

**Comment by nickme** [comment]
Pull request 95 contains the fix and the lsvmbus utility.
Closing.
