### ISSUE TITLE
Load hv_sock driver when the first AF_HYPERV socket is created

### ISSUE THREAD

**Issue by alexngmsft** [LIS/lis-next#92]

**Comment by nickme** [comment]
The hv_sock.ko module needs to be loaded before the first AF_HYPERV socket is created.  The easiest way is to persistently load the module at boot time.  This requires the system administrator perform following steps:
1.	Create the file /etc/sysconfig/modules/hv_sock.modules with the following contents:
#!/bin/sh
exec /sbin/modprobe hv_sock > /dev/null 2>&1
2.	Set the execute permissions on the hv_sock.modules file
chmod 755 /etc/sysconfig/modules/hv_sock.modules
The hv_sock module should now load during boot.
